import './globals.css' // Jika menggunakan CSS global

export const metadata = {
  title: 'Aplikasi Absensi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id">
      <body className="min-h-screen bg-gray-50">
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  )
}